IMAGE_UPLOAD_REQUEST = "image.upload.request"
IMAGE_SUBMITTED = "image.submitted"
INFERENCE_COMPLETED = "inference.completed"
ANNOTATION_STORED = "annotation.stored"
EMBEDDING_CREATED = "embedding.created"
QUERY_SUBMITTED = "query.submitted"
QUERY_COMPLETED = "query.completed"
ANNOTATION_CORRECTED = "annotation.corrected"